plugins:
  - jasmine
env:
  browser: true
  es6: true
  node: true
  jasmine: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
